/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try {
            Gson gson = new Gson();
            BufferedReader reader = Files.newBufferedReader(Paths.get("C:\\Users\\dc\\asac\\401\\quotes\\app\\src\\main\\resources\\recentquotes.json"));
//            String line = reader.readLine();
//            while (line != null) {
//                System.out.println(line);
//                line = reader.readLine();
//            }
            List<Quotes> quote = gson.fromJson(reader, new TypeToken<List<Quotes>>() {}.getType());
            reader.close();
            int min = 0;
            int max = quote.size()-1 ;
            System.out.println(quote.get((int) (Math.random()*(max- min+1)+ min)));

        } catch (IOException e){
            e.printStackTrace();
        }

    }

    }



